language: objective-c
osx_image: xcode7.1
xcode_project: KALTURAPlayerSDK.xcodeproj
xcode_scheme: KALTURAPlayerSDK
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
notifications:
  email:
    recipients:
      - itay.kinnrot@kaltura.com
      - eliza.sapir@kaltura.com
      - nissim.pardo@kaltura.com
      - noam.tamim@kaltura.com
    on_success: change
    on_failure: always
deploy:
  provider: script
  script: ./cocoapods-push.sh
  on:   # only deploy if building a tag, AND the tag is in the format digits.digits.digits
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
